In [143]:

def odd():
    my_list = list(range(10,30))
    return my_list[1::2]
odd()

[11, 13, 15, 17, 19, 21, 23, 25, 27, 29]

In [144]:
def display(num):
    for i in range(10,num):
        if i %2 != 0:
            print(i)
display(30)

11
13
15
17
19
21
23
25
27
29


In [145]:
display(30)

11
13
15
17
19
21
23
25
27
29


In [146]:
lst = list(range(10,30))

In [147]:
x = [x*100 for x in range(10,30) if x%2 !=0]

In [148]:
x

[1100, 1300, 1500, 1700, 1900, 2100, 2300, 2500, 2700, 2900]

### Numpy 
#### Numerical Python
This introduces multidimensional arrays(ND Arrays) which we know as lists in python. This adds new methods to manipulate arrays which are not in python lists. 
Numpy also makes it easier to identify and work with null values.

In [149]:
import numpy as np

In [150]:
import pandas as pd


In [151]:
type(None)

NoneType

In [152]:
ls1 = [[16,45,30,6,5],[6,None,8,70,8],[11,67,9,40,7]]

In [180]:
ls1[1][3]

70

In [154]:
len(ls1)

3

In [181]:
ls1.count(8)

0

In [156]:
type(np.nan)

float

In [157]:
arr1 = np.array(ls1,dtype=np.float)

In [158]:
arr1

array([[16., 45., 30.,  6.,  5.],
       [ 6., nan,  8., 70.,  8.],
       [11., 67.,  9., 40.,  7.]])

In [159]:
arr2 = arr1

In [160]:
type(arr2)

numpy.ndarray

In [161]:
arr2

array([[16., 45., 30.,  6.,  5.],
       [ 6., nan,  8., 70.,  8.],
       [11., 67.,  9., 40.,  7.]])

In [162]:
null = np.isnan(arr1)

In [163]:
null

array([[False, False, False, False, False],
       [False,  True, False, False, False],
       [False, False, False, False, False]])

In [164]:
arr1[null] = 0

In [165]:
arr1

array([[16., 45., 30.,  6.,  5.],
       [ 6.,  0.,  8., 70.,  8.],
       [11., 67.,  9., 40.,  7.]])

In [166]:
arr1.shape

(3, 5)

In [167]:
arr1.size

15

In [168]:
arr1

array([[16., 45., 30.,  6.,  5.],
       [ 6.,  0.,  8., 70.,  8.],
       [11., 67.,  9., 40.,  7.]])

In [171]:
arr2

array([[16., 45., 30.,  6.,  5.],
       [ 6.,  0.,  8., 70.,  8.],
       [11., 67.,  9., 40.,  7.]])

In [172]:
arr1 = np.array(ls1,dtype=np.float)

In [173]:
arr1

array([[16., 45., 30.,  6.,  5.],
       [ 6., nan,  8., 70.,  8.],
       [11., 67.,  9., 40.,  7.]])

In [174]:
arr2 = arr1.copy()


In [175]:
arr2

array([[16., 45., 30.,  6.,  5.],
       [ 6., nan,  8., 70.,  8.],
       [11., 67.,  9., 40.,  7.]])

In [176]:
arr1[np.isnan(arr1)] = 0

In [177]:
arr1

array([[16., 45., 30.,  6.,  5.],
       [ 6.,  0.,  8., 70.,  8.],
       [11., 67.,  9., 40.,  7.]])

In [178]:
arr2

array([[16., 45., 30.,  6.,  5.],
       [ 6., nan,  8., 70.,  8.],
       [11., 67.,  9., 40.,  7.]])